### ISSUE TITLE
feat: Helm Manifet Compare

### ISSUE THREAD

**Issue by ShashwatDadhich** [devtron-labs/dashboard#1169]
🔖 Feature description

Helm apps > Configure > Manifest output (Ability to compare with Manifest output of previous deployments)

🎤 Pitch

Ability to compare helm manifest

✌️ Solution

Add a button to comapre manifests same as that of compare values.

🔄️ Alternative
No response

👀 Have you spent some time to check if this issue has been raised before?
 I checked and didn't find similar issue

🏢 Have you read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)?
 I have read the Code of Conduct

**Comment by abhibhaw** [comment]
Fixed with attached PR
