### ISSUE TITLE
fix: UI fixes in the App Details > Networking > Services

### ISSUE THREAD

**Issue by dhananjay0601** [devtron-labs/dashboard#1253]
**Please Describe The Problem To Be Solved**
-> There are some UI leaks on App Details > Networking > Services Page where list of the port numbers is displaying 
-> Extra space over the List of Port Numbers 
-> Double copy icons on the port List dropDown.
<img width="111" alt="Screenshot 2023-09-04 at 11 04 17 AM" src="https://github.com/devtron-labs/dashboard/assets/124036328/181fdd71-05ad-49ee-8539-0ceeb87c9da2">

<img width="222" alt="Screenshot 2023-09-04 at 11 04 28 AM" src="https://github.com/devtron-labs/dashboard/assets/124036328/92a201b1-ea44-4303-b105-afd48841b495">

-> During copying the URL there are spaces though there shouldn't be any.
-> Missing Copy Icon
<img width="845" alt="Screenshot 2023-09-04 at 11 06 53 AM" src="https://github.com/devtron-labs/dashboard/assets/124036328/b4b73dde-312c-4982-aed4-966b218ecd4d">

**(Optional): Suggest A Solution**
(Replace This Text: A concise description of your preferred solution. Things to address include:
* Details of the technical implementation
* Tradeoffs made in design decisions
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by abhibhaw** [comment]
Fixed with attached PR
