### ISSUE TITLE
feat: Edit manifest option for devtron/helm apps.

### ISSUE THREAD

**Issue by iamayushm** [devtron-labs/dashboard#706]
**Please Describe The Problem To Be Solved**
Currently manifest can be edited in resource browser but we are not able to edit manifest of same resource on app details page.

**(Optional): Suggest A Solution**
- manifest component on FE should be modified so that we can edit manifest for devtron/helm apps.

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

**Comment by abhibhaw** [comment]
Fix already merged with another PR
